OrdererOrgs:
  - Name: OrdererOrg
    Domain: example.com
    # EnableNodeOUs: true   # ← Also enable for orderer org
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    # EnableNodeOUs: true   # ← This is REQUIRED
    Template:
      Count: 1
    Users:
      Count: 1
